cap-js/cds-typer

- .gitignore
- package.json
Generates HTML typedoc to `doc/html/` and the help text to `doc/cli.txt`.
> Add NPM Scripts to Generate Doc

- CHANGELOG.md
- lib/components/resolver.js
- lib/visitor.js
- test/ast.js
- test/unit/arrayof.test.js
- test/unit/files/arrayof/model.cds
Fixes https://github.com/cap-js/cds-typer/issues/20
Allows the use of 
```cds
entity A { ... }
entity B {
x: array of A;
y: many A;
}
```
> Support `array of` Syntax

- CHANGELOG.md
- lib/visitor.js
Fixes https://github.com/cap-js/cds-typer/issues/19
If the project's _[j|t]sconfig.json_ contains `checkJs: true`, accessing properties of generated types that are not explicitly declared will cause an error.
```cds
entity Books { ID: UUID; title: String; }
```
```ts
const { Book } = require('...')
service.before('CREATE', Book, ({data}) => {
data.ID  // fine
data.title  // fine
data.numberOfPages // not part of model definition, causes an error
})
```
> Strict Properties

- CHANGELOG.md
- lib/components/resolver.js
- test/unit/output.test.js
Fixes https://github.com/cap-js/cds-typer/issues/18
> Change Generated Type for cds.Date et al. to string

- CHANGELOG.md
- lib/components/inline.js
- lib/components/resolver.js
- lib/file.js
- lib/visitor.js
- test/unit/events.test.js
- test/unit/files/events/model.cds
Fixes https://github.com/cap-js/cds-typer/issues/32
Supports the syntax
```cds
event Foo: { id: Integer; name: String }
```
and converts it into a class _with attached properties_
```ts
class Foo {
id: number
name: string
}
```
> Support `event` Syntax

- CHANGELOG.md
- lib/file.js
- lib/visitor.js
Bound actions before only had their type definitions generated. They now also generate an initialiser stub to appease `tsc` when `"strict": true` is set in the project's _tsconfig.json_.
```cds
entity Books as projection on my.Books actions {
function getDetails(test : String) returns { test : String };
}
```
```ts
export function _BookAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
return class Book extends Base {
...
getDetails: (test: string) => { test?: string; } = undefined as unknown as this['getDetails']  
//                                              /
//                                            new
}
}
```
> Initialise Bound Actions

- CHANGELOG.md
- lib/file.js
Setting `noUnusedParameters` in a project's tsconfig.json would bring up an error in a generated base type, which had to be stubbed. This PR prefixes said parameter to make sure `tsc` won't complain about this.
> Prefix Unused Parameter in Base Type

- CHANGELOG.md
- lib/components/resolver.js
- test/unit/files/type/model.cds
- test/unit/type.test.js
When referencing `type` definitions, their name is no longer inflected, since no singular/ plural forms are generated for them.
```cds
type Points: { x: Integer; y: Integer }
type Lines: array of Points;
```
```ts 
export class Points { ... }  // only 'Points', no 'Point'
export class Lines {
points: Array<Points>  // not 'Point'
}
> Do not inflect type definitions

- CHANGELOG.md
- lib/components/resolver.js
- test/unit/actions.test.js
- test/unit/files/actions/model.cds
```cds
entity Foo {}
actions {
action bar (x: many $self) 
action baz (x: $self)
}
```
> Support `$self` Syntax in Bound Action Parameters

- CHANGELOG.md
- lib/visitor.js
- test/unit/files/references/model.cds
- test/unit/references.test.js
```cds
entity Foo {
key first_key: UUID;
key second_key: String;
}
entity Bar {
key id: Integer;  // required for composition of many ... to work.
assoc_one: Association to one Foo;
};
```
now results in
```ts
class Foo { 
first_key?: string
second_key?: string
}
class Bar {
id?: number
assoc_one?: Association.to<Foo>
assoc_one_first_key?: string  // new ✨
assoc_one_second_key?: string  // new ✨
}
```
(more or less)
> Maintain Foreign Keys

- CHANGELOG.md
- lib/file.js
- lib/visitor.js
Fixes https://github.com/cap-js/cds-typer/issues/53
> Use `@singular`/`@plural` in Generated `index.js` Files

- CHANGELOG.md
- lib/util.js
- lib/visitor.js
- test/unit/files/references/model.cds
- test/unit/references.test.js
```cds
// model.cds
entity C {
key y: String;
}
entity B: C {
key x: String;
}
entity A {
b: Association to one B
}
```
```ts
// generated index.ts
class A {
b: Association.to<B>
b_x: string
b_y: string  // ✨ new, B inherited this from aspect C
}
```
Also fixes https://github.com/cap-js/cds-typer/issues/62
> Generate Inherited Key Properties 

- package-lock.json
- package.json
Using `^` with `0.` releases never upgrades to new ones → always prefer using `>=` instead.
And because of that, we were not able to upgrade `typescript` to the latest version `5.2.2`. 
Better even: I'd prefer to not have `typedoc` being used at all. → We have to manage what 3rd party/OSS tools we use, otherwise `cap/dev` exceeds all limits, getting ever more heavyweight.
> Upgrading typedoc

- CHANGELOG.md
- lib/csn.js
- lib/visitor.js
- test/unit/draft.test.js
- test/unit/enum.test.js
- test/unit/files/foreignkeys/model.cds
- test/unit/foreignkeys.test.js
Fixes https://github.com/cap-js/cds-typer/issues/62
While foreign keys were propagated through inheritance over arbitrary depth, structured fields that were keys and contained keys itself propagated only one level of keys. This is fixed now.
> Propagate Multi-Level Keys Recursively

- lib/file.js
- test/ast.js
- test/unit/actions.test.js
- test/unit/arrayof.test.js
- test/util.js
Instead generating actions/ functions as
```ts
f: (a: string, b: number) => boolean
```
they are now instead generated as
```ts
f: {
(a: string, b: number): boolean,
__parameters: { a: string, b: number },
__returns: boolean
}
```
this leaves `f` as callable, but also injects the parameter list as explicit object into `f`. This makes it far more easy to extract the parameter types on CDS side, where we need them in context of handler implementations.
> Generate utility object in lambdas

- CHANGELOG.md
- lib/file.js
- lib/visitor.js
- test/ast.js
- test/unit/actions.test.js
- test/unit/arrayof.test.js
Bound functions/ actions are now generated into a `static` property named `actions`. (They were formally generated as instance methods.)
```cds 
entity E {}
actions {
action f ();
function g ();
}
}
```
⬇️
```ts
class E {
static actions: {
f: () => void,
g: () => void
}
}
```
> Make Bound Functions Static

- CHANGELOG.md
- lib/visitor.js
Using `typeof X` with `X` being inherited from another aspect in combination with `cds.load(..., flavor: {'xtended'})` currently generates ominous entities that are not resolved. They will now be skipped with an appropriate error message.
```cds
// model.cds
entity Parent {
property: String;
}
entity Child: Parent {
reference: type of property
}
```
⬇️
```
[ERROR] Skipping unresolved entity: {"name":{"ref":["Parent","property"]},"_unresolved":true,"@odata.draft.enabled":false}
```
> Skip entities in printout if they are unresolved

- CHANGELOG.md
- lib/components/enum.js
- lib/components/resolver.js
- lib/csn.js
- lib/file.js
- lib/printers/enum.js
- lib/visitor.js
- test/ast.js
- test/unit/enum.test.js
```cds
entity E {
x: enum of String {
a = 'A';
b = 'B';
}
}
```
```ts
enum E_x {
a = 'A',
b = 'B'
}
class E {
static x = { enum: E_x }
x: E_x
}
```
> Include Inline Enum Properties in Generated Types

- lib/components/enum.js
- lib/components/resolver.js
- lib/file.js
- lib/visitor.js
- test/unit/enum.test.js
Anonymous (inline) enums had before been generated to match exactly with how they were defined in CSN.
This led to long-winded calls with additionally wrapped properties:
```js
myBook.genre = Books.definitions.genre.enum.Horror.val
```
This PR flattens the generated enums and produces their runtime equivalent in the respective `index.js` files.
```js
myBook.genre = Books.genre.Horror
``` 
Their level of convenience should therefore now on a par with named enums.
> Concise Anonymous Enums

- CHANGELOG.md
- lib/compile.js
- lib/components/resolver.js
- lib/visitor.js
- test/unit/autoexpose.test.js
- test/unit/files/autoexpose/schema.cds
- test/unit/files/autoexpose/service.cds
Due to the use of `xtended` CSN flavour, cds-typer currently does not generate code for auto exposed entities in services.
This PR makes sure those entities are printed as well _at a high performance price_, so this feature will have to be revisited soon.
This is closely related to https://github.com/cap-js/cds-typer/issues/77, as `.texts` entities are also included in `inferred`.
> Auto Expose

- lib/components/resolver.js
- lib/file.js
- lib/visitor.js
Files that represent a service now have a default export that roughly mimics the structure of services within CSN. 
As such, they currently expose a property `name` that contains the clean name of the service.
```cds
service FooService { ... }
```
```ts
// index.ts
export default { name: 'FooService' }
```
```js
// index.js
module.exports.default = { name: 'FooService' }
```
> Print Service Names as Default Export 

- CHANGELOG.md
- lib/visitor.js
Generated classes (both for singular and plural) will now contain a static `.name` property which contains the fully qualified name of the entity it was generated from.
```cds
namespace 'sap.bookshop';
entity Books {}
```
```ts
// sap/bookshop/.index.ts
class Book {
static name = 'sap.bookshop.Books'
}
class Books extends Array<Book> {
static name = 'sap.bookshop.Books'
}
```
This allows the class _and its transpiled form_ to be used as parameter for CDS functions that expect CSN definitions. Those will look for a `.name` property and use that as lookup key in the compiled CSN.
This PR is therefore a step towards using the transpiled `index.js` files in a TypeScript context.
Note that `.name` is actually a [reserved …
> Generate Static Name Property

- CHANGELOG.md
- lib/components/resolver.js
Fixes https://github.com/cap-js/cds-typer/issues/97
> Add `Readable` as Possible Type for `cds.LargeBinary`

- CHANGELOG.md
- lib/components/enum.js
Fixes https://github.com/cap-js/cds-typer/issues/99
Enums that did not provide an explicit value for enum fields would have `undefined` for their values in the generated _index.js_ files before.
```cds
// model.cds
type Foo : String enum {
Bar;
Baz = "baz";
}
```
```js
// index.js
const Foo = {
Bar: undefined,
Baz: "baz"
}
```
To rectify this, the field's name is now used as fallback value:
```js
// index.js
const Foo = {
Bar: "Bar",
Baz: "baz"
}
```
> Default Enum Values to Name

- test/ast.js
- test/unit/output.test.js
For (more) streamlined testing API across JS/TS.
> Wrap fs.read in JS wrapper initialisation

- CHANGELOG.md
- lib/visitor.js
- test/unit/excluding.test.js
- test/unit/files/excluding/model.cds
Fixes https://github.com/cap-js/cds-typer/issues/117
```cds
entity Foo {
a: Int;
b: Int;
}
service S {
entity Bar as projection on Foo excluding { a };
}
```
```ts
// index.ts
class Foo {
a: number
b: number
}
// S/index.ts
class Bar {
b: number
}
```
> Do Not Emit Elements That Are Part of `excluding` Clause

- CHANGELOG.md
- lib/csn.js
- lib/visitor.js
- package.json
- test/ast.js
- test/unit/enum.test.js
- test/unit/files/views/model.cds
- test/unit/output.test.js
- test/unit/references.test.js
- test/unit/views.test.js
Fixes https://github.com/cap-js/cds-typer/issues/121
```cds
entity Foo {
a: Integer;
b: String;
}
entity Bar as select from Foo {
a,
a as alias
};
```
```ts
class Foo {
a: number
b: string
}
class Bar {
a: number
alias: number
}
```
> Generate View Types

- CHANGELOG.md
- lib/csn.js
- lib/visitor.js
Keys are now propagated through both flavours of CSN (inferred and xtended) and retrieved from them as well when printing out the classes.
We need to consider both flavours, as xtended contains inherited keys, and inferred contains keys from queries entities.
> Retrieve keys from both flavours of CSN

- CHANGELOG.md
- lib/components/enum.js
- lib/visitor.js
- test/ast.js
- test/unit/enum.test.js
- test/unit/files/enums/actions.cds
Fixes https://github.com/cap-js/cds-typer/issues/137
Using an externally (read: not inline) defined enum as type for an action parameter would incorrectly assume non-string values. This is now fixed by instead resolving the enum's name.
> Resolve externally defined enums in action parameters

- test/ast.js
- test/unit/actions.test.js
- test/unit/arrayof.test.js
- test/unit/autoexpose.test.js
- test/unit/delimited.test.js
- test/unit/draft.test.js
- test/unit/enum.test.js
- test/unit/events.test.js
- test/unit/excluding.test.js
- test/unit/foreignkeys.test.js
- test/unit/hana.test.js
- test/unit/inline.test.js
- test/unit/notnull.test.js
- test/unit/output.test.js
- test/unit/references.test.js
- test/unit/scoped.test.js
- test/unit/type.test.js
- test/unit/typeof.test.js
- test/unit/views.test.js
- test/util.d.ts
- test/util.js
Considerably clean up unit tests, make them more compact, and reduce probability to run into race conditions during tests.
> Refactor Tests

- CHANGELOG.md
- lib/components/reference.js
- lib/components/resolver.js
- lib/file.js
- test/unit/files/typeof/external.cds
- test/unit/files/typeof/model.cds
- test/unit/typeof.test.js
Fixes https://github.com/cap-js/cds-typer/issues/93
> Allow typeof syntax on externally defined enums

- CHANGELOG.md
- lib/file.js
- package.json
As CDS `type` definitions no longer receive an inflection as of 0.18.0, they instead use `Array<MyType` for their plural.
This particular kind of plural should _not_ be printed to the corresponding _index.js_ files, as that would lead to:
```js
module.exports.Array<MyType> = ...
```
which is a syntax error.
> Don't print out array type for cds types

- CHANGELOG.md
- lib/compile.js
- package-lock.json
- package.json
When resolving `@sap/cds` to start the compiler cds-typer will now try the project's _node_modules_ directory first and prefer to use the installation it finds there.
The former behaviour would under certain dev setups lead another `@sap/cds` version being used that could have lacked certain features.
> Streamline Resolution of `@sap/cds`

- CHANGELOG.md
- lib/components/resolver.js
- lib/visitor.js
Types would sometimes be considered builtin even if they weren't. Specifically, this happened when a type started with `cds.` in parameter types. We now stricten this check to use an allow-list instead of relying on the prefix.
> Introduce stricter check for builtin types

- lib/components/resolver.js
- test/unit/enum.test.js
- test/unit/files/enums/enumtyperef.cds
Partially addresses https://github.com/cap-js/cds-typer/issues/171
For the example given by the reporter cds-typer now infers `string` as the type instead of crashing the type generation process.
But we still need to precisely refer to the type in question and also allow it in general `type` definitions and return types. Therefore not closing the issue yet.
> Fix runtime error when using typeof in enum declaration

- CHANGELOG.md
- lib/visitor.js
Only `declare` classes representing events, as their properties are not optional, so we'd have to initialise them awkwardly.
> Declare event classes

- CHANGELOG.md
- lib/compile.js
Fixes https://github.com/cap-js/cds-typer/issues/238
(was actually already done, but parameters passed to the CLI now take precedence over `cds.env`)
> Use CLI parameters over `cds.env`

- cds-plugin.js
- package.json
Fixes https://github.com/cap-js/cds-typer/issues/248
> Add missing file entry in package.json for build plugin

- CHANGELOG.md
- lib/file.js
Fixes https://github.com/cap-js/cds-typer/issues/260
> Do not add is_singular to singulars that retain the original name

- CHANGELOG.md
- cds-plugin.js
Instead of looking for a tsconfig.json, which users may be using to configure their LSP in a JS project, we now check if the project's package.json contains a dependency to `typescript`.
> Change TS detection mechanism

- CHANGELOG.md
- lib/components/wrappers.js
- lib/file.js
- lib/visitor.js
- package-lock.json
- package.json
- test/ast.js
- test/smoke/setup.js
- test/tscheck.js
- test/unit/actions.test.js
- test/unit/arrayof.test.js
- test/unit/file.test.js
- test/unit/hana.test.js
- test/unit/setup.js
- test/unit/type.test.js
- test/util.js
Default export for the `<Service>.ts` file is now a service class:
```ts
import cds from '@sap/cds'
export default class extends cds.Service { ... }
```
Which declares functions for each unbound action, reusing the existing type:
```ts
export default class extends cds.Service {
declare submitOrder: typeof submitOrder
}
```
The action type gets a second signature for the 'named/object' call style supported by Node.js:
```ts
export declare const sumitOrder: {
// positional
(book: __.DeepRequired<Book>['ID'], quantity: number | null): Promise< {
stock?: number | null,
} | null | null> |  {
stock?: number | null,
} | null | null
// named
({book, quantity}: {book: __.DeepRequired<Book>['ID'], quantity: number | null}): Promise< {
stock?: number | null,
} | null | null> |  {
stock?: number | …
```
> Signatures for unbound actions + named call style

- CHANGELOG.md
- lib/file.js
- lib/resolution/resolver.js
- lib/visitor.js
- test/ast.js
- test/unit/actions.test.js
- test/unit/files/actions/model.cds
If a `@Core.OptionalParameter` annotation is set on an operation parameter, mark the property as optional in the named call style.
The actual annotation is not fixed yet, but this is the state of discussion.
Resulting `.ts` file with `?` modifiers:
```ts
export declare const submitOrder: {
// positional
(book: ..., quantity: number | null): ...
// named
({book, quantity}: {book: ..., quantity?: number | null}): ...
...
}
```
The existing default for mandatory/optional is not changed, so no migration expected.
Continuation of https://github.com/cap-js/cds-typer/pull/291
> Support optional operation parameters

- lib/visitor.js
`EntityRepository` offers [`getByFqOrThrow`](https://github.com/cap-js/cds-typer/blob/main/lib/resolution/entity.js#L154) which returns `EntityInfo` (instead of `EntityInfo | null`,  as `getByFq` does), and thus eliminates the need to check for `null` to appease the type system.
Should only be used where we are certain the entity actually exists. For example, when iterating over all entitiy names and looking them up in our CSN.
> Use getByFqOrThrow where appropriate

- lib/file.js
Only import `@sap/cds` iff at least one class extending `cds.Service` is present in that file. Otherwise, strict configs would find fault with the unused variable.
> Make import of cds conditional

- CHANGELOG.md
- lib/file.js
- lib/visitor.js
- test/unit/files/actions/model.cds
- test/unit/files/actions/model.ts
Actions for ABAP RFC modules should only be callable with named parameters. Such modules have 'parameter categories' (import/export/changing/tables) that cannot be called in a flat order.
> Disable positional call style for ABAP RFC actions

- CHANGELOG.md
- lib/components/enum.js
- lib/file.js
- lib/visitor.js
- test/unit/files/enums/model.cds
Add docs to exposed artifacts so that they appear in code completion etc.
- for enums: on the exported const and the element pointing to it
- for entities: on the exported class, not the aspect
> Add docs for enums, fix it for entities

- CHANGELOG.md
- lib/cli.js
- lib/components/javascript.js
- lib/file.js
- lib/typedefs.d.ts
- lib/visitor.js
- test/ast.js
- test/unit/entitiesproxy.test.js
Wrapping the `module.exports` in `Proxy` objects removes the need for dynamic imports everywhere.
- new `module.exports` in `index.js` of namespace `_`  
- wrapping the entity `module.exports` in the new `createEntityProxy` function  
- The `set`-trap in the Proxy and the `customProps` are mainly for the inline enums, otherwise they could not be accessed
> feat: use `Proxy`s for entity exports in index.js files

- lib/components/javascript.js
- test/unit/entitiesproxy.test.js
- test/unit/files/entitiesproxy/nonamespace.cds
- test/unit/files/entitiesproxy/service.cds
I discovered some bugs in my proxy creator function.
1. The fully qualified name will be wrong if an empty namespace is passed to the function
2. for some reason the cds.entities[name] variant can only used if at least 2 CDS files are located in the `/db` folder.
Only runtime tests could discover those issues.
@daogrady  Are there runtime tests in the project or is it planned to have them? For features such as the proxy function it would be great.
> Fixes cds.entities and entity name issues in proxy function

- CHANGELOG.md
- lib/resolution/resolver.js
- test/unit/actions.test.js
- test/unit/files/actions/model.cds
- test/unit/files/actions/model.ts
Replace the use of `@Core.OptionalParameter` for optional parameters (which was an intermediate solution anyways) by evaluating CSN's `notNull` property.  This is in line with the decision in the CDS spec meeting and with what RFC importer now generates.
Note that this formally inverses the default for optional parameters:
- They are all optional by default, which is how the runtime treats it.
- Mandatory parameters now have to be marked with `notNull` (or `not null` in CDL).
> Determine optional action parameters from CSN's `notNull`

- CHANGELOG.md
- lib/cli.js
- lib/compile.js
- lib/components/inline.js
- lib/config.js
- lib/file.js
- lib/resolution/resolver.js
- lib/typedefs.d.ts
- lib/util.js
- lib/visitor.js
- test/unit/cliopts.test.js
- test/unit/cliopts/db/schema.cds
- test/unit/cliopts/package.json
- test/unit/tsCheckAndRun.test.js
- test/util.js
Configuration parameters can now be passed either in camelCase or snake_case. This mechanism works for both CLI parameters, as well as for options passed via `cds.env`. The order of precedence is (still):
CLI parameters > `cds.env` > default values
> Snake case options

- lib/cli.js
`cds-typer --help` would display each option twice. This PR groups them instead.
> Avoid duplicates in --help

- cds-plugin.js
- lib/cli.js
- lib/config.js
Fixes https://github.com/cap-js/cds-typer/issues/323
> Fix output path in build task

- CHANGELOG.md
- lib/components/basedefs.js
- lib/components/wrappers.js
- lib/resolution/resolver.js
- lib/visitor.js
- test/ast.js
- test/unit/files/keys/model.cds
- test/unit/files/keys/model.ts
- test/unit/foreignkeys.test.js
- test/unit/keys.test.js
- test/unit/references.test.js
> Generate static .keys property

- lib/components/inline.js
- lib/file.js
- lib/resolution/resolver.js
- lib/visitor.js
- Inline types (with `--inlineDeclarations structured` option)
```ts
export function _CompanyAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
return class Company extends Base {
address?: {
place?: string | null,
zip?: string | null,
info?: {
a?: string | null,
a_a?: {
a?: string | null,
} | null,
} | null,
} | null;
};
}
```
- Bound Actions
```ts
export function _CompanyAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
return class Company extends Base {
declare static readonly actions: {
changeLeader: {
// positional
(leaderName: string | null): any
// named
({leaderName}: {leaderName?: string | null}): any, 
// metadata (do not use)
__parameters: {leaderName?: string | null}, __returns: any, kind: 'action'}
}
};
}
```
- with `--inlineDeclarations …
> fix: properly align all types of class properties (action, inline types, statics, ...)

- CHANGELOG.md
- package.json
Adds the build task, so that it is recognized for validation & autocomplete in the package.json.
> feat: cds schema for typescript build task

- CHANGELOG.md
- lib/components/basedefs.js
- lib/components/wrappers.js
- lib/visitor.js
- test/unit/files/elements/model.cds
- test/unit/files/elements/model.ts
Enables proper access to all entity elements of the underlying `LinkedDefinition`.
e.g.
```cds
entity Books : cuid {
title : String;
stock : Integer;
}
```
new property `elements` allows access to all defined elements of the entity and access the underlying `LinkedDefinition` of those elements.
```ts
import { Book } from "#cds-models/my/bookshop";
import cds from "@sap/cds";
if (Book.elements.ID instanceof cds.builtin.classes.UUID) console.log("ID is of type UUID");
if (Book.elements.stock instanceof cds.builtin.classes.Integer) console.log("stock is of type Integer");
```
> feat: add static property `elements` to entity classes

- CHANGELOG.md
- lib/resolution/resolver.js
- test/unit/actions.test.js
- test/unit/files/actions/model.cds
- test/unit/files/actions/model.ts
The fix on #332.
Explaining comment is [here](https://github.com/cap-js/cds-typer/pull/332#discussion_r1799647831).
> Fix array-like params in CDS functions/actions

- CHANGELOG.md
- lib/components/class.js
- lib/components/enum.js
- lib/components/inline.js
- lib/components/wrappers.js
- lib/file.js
- lib/resolution/entity.js
- lib/visitor.js
- library/cds.hana.ts
- test/tscheck.js
- test/unit/files/actions/model.ts
- test/unit/files/keys/model.ts
Only add `override` modifier to `kind` property iff any parent class actually has such a property to override.
This change is implicitly tested by having added `strict: true` to the transpilation tests in `tscheck.js`.
Fixes https://github.com/cap-js/cds-typer/issues/273
Generally, the creation of class members has been streamlined to avoid typos and incorrect order/ combination of modifiers via `lib/components.class::createMember` instead of concatenating strings manually.
Also streamlined use of `Buffer.add` to accept scalar strings, array of strings, and functions returning strings, to enable `buffer.add(xs)` over `xs.forEach(x => buffer.add(x))`.
Also added `buffer.blankLine()` to replace the somewhat obscure `buffer.add('')`
> Safely override `.kind` and `Buffer` improvements

- CHANGELOG.md
- cds-plugin.js
- package-lock.json
- package.json
A bug somewhere in the mixture of Windows, shell quoting, `tsc`, and node's `exec` function leads to corrupt, partially quoted paths.
No better fix is known than to convert Windows' `\` to `/` with which the issue no longer occurs.
Fixes #374
> Do not fail on Windows with `EINVAL`

- lib/file.js
- lib/visitor.js
- test/tscheck.js
- test/unit/files/actions/model.cds
- test/unit/files/actions/model.ts
- test/unit/files/draft/model.ts
Fixes https://github.com/cap-js/cds-typer/issues/391
We recently introduced a distinction between entities that have no actions ( = empty `.actions` property) and ones that do. In one of these branches, the required `overrides` modifier got lost. This PR streamlines both cases and reintroduces the modifier.
It also strictens the effective tsconfig that is used for transpilation tests to catch this kind of regression in the future.
> Reintroduce declare modifier on actions

- lib/components/wrappers.js
- lib/visitor.js
- test/ast.js
- test/unit/files/keys/model.cds
- test/unit/keys.test.js
Fixes https://github.com/cap-js/cds-typer/issues/391
Having two entities that mutually reference each other, and also extend a common ancestors that has a key would throw of the `KeysOf` type.
In the minimal model
```cds
using { cuid } from '@sap/cds/common';
entity Foo: cuid {
bar: Association to Bar
}
entity Bar: cuid {
foo: Association to Foo
}
```
TS would complain about at least one resulting aspect function, as the inherited `ID` property was supposedly missing from the descendents `.keys` property.
```ts
class cuid {
ID: Key<string>
static keys: KeysOf<cuid>
}
class Foo extends cuid {
static keys: KeysOf<Foo>  // error: .keys should have a property "ID", which is missing
}
```
With this PR, each parent's `typeof .keys` is explicitly repeated:
```ts
class cuid {
ID: Key<string> …
```
> Propagate keys from parents down to child entities

- lib/util.js
Finding a package.json in a parent directory (mono repo scenario) would still try to open package.json in the CWD, which would then fail. This fix now prepends the directory the file was found in, making it an absolute path instead.
> Use full file path for package.json

- .github/workflows/enforce-changelog.yml
Adds a workflow that enforces changes to CHANGELOG.md in new PRs.
Check can be bypassed by adding the `skip changelog` label to a PR.
See: https://github.com/cap-js/cds-typer/actions/runs/11934582832/job/33263999681?pr=401
> Add enforce changelog workflow

- CHANGELOG.md
- lib/cli.js
- lib/config.js
- package.json
Change default value for `outputDirectory` from `./` to `./@cds-models` when executed in a CAP project.
This PR does _not_ include changing the default for the target model files to `"*"`.
> Read default output @cds-models from package.json

- .github/workflows/dependabot-skip-changelog.yml
Automatically ad the `skip changelog` label to avoid blocking PRs from Dependabot.
> Add script to automatically label dependabot prs

- CHANGELOG.md
- lib/config.js
Fixes https://github.com/cap-js/cds-typer/issues/432
> Act on finding "type":"module"

- .github/workflows/dependabot-skip-changelog.yml
All PRs are by default blocked if they didn't make any change to CHANGELOG.md, unless they have the `skip changelog` label. This requirement does not hold for dependabot PRs. So any PR opened by dependabot should automatically be assigned the `skip changelog` label. This [did not work before](https://github.com/cap-js/cds-typer/actions/runs/12353218335/job/34471863295?pr=441), likely because of the missing permissions that are added with this PR.
> Add permissions to label workflow

- CHANGELOG.md
- lib/file.js
- lib/visitor.js
- test/unit/files/actions/model.ts
Fixes https://github.com/cap-js/cds-typer/issues/288
Requires https://github.com/cap-js/cds-types/pull/390
See https://github.com/chgeo/issue-named-service-exports/issues/1
> Export service as unnamed class

- .github/workflows/enforce-changelog.yml
```yaml
cap-js/.github/.github/workflows/enforce-changelog.yml@ci/addEnforceChangeLog
````
will be replaced by 
```yaml
cap-js/.github/.github/workflows/enforce-changelog.yml@main
```` 
once https://github.com/cap-js/.github/pull/15 is merged
> ci(enforce-changelog): use org workflow

- CHANGELOG.md
- cds-plugin.js
- lib/cli.js
- package.json
Setting `cds.env.typer.skip_build_task` to `true` will now disable the `typescript` build task.
Currently, the only way to achieve this is to explicitly call `cds build --for x --for y --for z` with all build tasks, except for `typescript`.
This was requested by users who would like to perform the required build steps themselves.
PR is best viewed with hidden whitespace changes.
> Add flag to explicitly disable the typescript build task

- .github/workflows/check-schema-integrity.yml
cds-typer supports a bunch of [CLI parameters](https://github.com/cap-js/cds-typer/blob/main/lib/cli.js#L146) that can all also be specified via `cds.env`.
To receive code completion for these options when editing a project's _package.json_, these options, default values, and descriptions also have to be maintained [in cds-typer's _package.json_](https://github.com/cap-js/cds-typer/blob/main/package.json#L69).
The latter can be generated automatically using [a utility script](https://github.com/cap-js/cds-typer/blob/main/scripts/write-cds-typer-schema.js). But if anyone adds a new configuration option and forgets to run this script, the code completion will be incorrect.
The workflow introduced in this PR therefore blocks any PR where the author apparently forgot to run the script.
> Add schema consistency check

- CHANGELOG.md
- lib/cli.js
- lib/resolution/builtin.js
- lib/resolution/resolver.js
- lib/typedefs.d.ts
- package.json
- test/unit/output.test.js
Fixes https://github.com/cap-js/cds-typer/issues/483
> `cds.Binary` → `Buffer`, `cds.LargeBinary` → `Readable`

- eslint.config.js
- package-lock.json
- package.json
Removes `globals` package and instead uses the globals object shipped with sap/cds' eslint config.
> Remove use of globals package with mirrored values from sap/cds

- CHANGELOG.md
- lib/cli.js
- lib/compile.js
- lib/typedefs.d.ts
- package.json
Setting `cds.typer.cache = 'blake2s256'` hashes the extended model and compares it to the hash of the previous run read from disk (if it exists). If the model has not changed, cds-typer will end the run immediately at this point.
cds-typer currently needs the inferred and xtended flavour of a model for a complete run. So when actually running, it performs `cds.load` twice, considerably increasing runtime.
With the `cache` setting active, it loads the xtended model first, checks the hash, and if the hash has not changed, does not perform the second `cds.load`. So we should see a runtime improvement of about 50% for the initial model loading when the cache is hit.
File IO is also cut down in case of a cache hit, as no files have to be written.
A quick test with a model of ~8MB in size …
> Add hashing

- CHANGELOG.md
- cds-plugin.js
Running `cds w` in your project will now initially run `cds-typer` if no `@cds-models` folder (or to whatever it is configured via `cds.typer.output_directory`) doesn't exist.
It does not run if this directory exists.
This feature is especially useful when you check out a CDS project and immediately dive into `cds w` from the CLI.
> Run typer once before cds watch starts

- CHANGELOG.md
- lib/resolution/resolver.js
- test/unit/aspects.test.js
- test/unit/files/aspects/model.cds
Fixes https://github.com/cap-js/cds-typer/issues/547
Compositions targeting aspects, instead of entities, would carry this information in a property `targetAspect`, rather than `target`. This PR falls back to resolving `targetAspect` when `target` can not be resolved.
> Resolve composition aspect targets

- CHANGELOG.md
- lib/components/property.js
- test/ast.js
- test/smoke/transpilation.test.js
- test/unit/actions.test.js
Fix for #545.
- Changes the check on adding a declare modifier to properly handle type definitions
- Sets properties as non optional in the transpilation test to avoid future errors
> Fix declare statement for type definitions while optional properties are disabled

- eslint.config.js
- package-lock.json
- package.json
- test/ast.js
- test/unit/keys.test.js
- introduce camelcase rule to config
- replace deprecated `@stylistic/eslint-plugin-js` with `@stylistic/eslint-plugin`
- fix some minor lint issues
> chore: Add camelcase rule

- CHANGELOG.md
- lib/cli.js
- lib/file.js
- lib/resolution/entity.js
- lib/typedefs.d.ts
- package.json
- test/config.js
- test/smoke/transpilation.test.js
- test/unit/actions.test.js
- test/unit/draft.test.js
- test/unit/enum.test.js
- test/unit/excluding.test.js
- test/unit/tsCheckAndRun.test.js
- test/util.js
- testing.md
_It partially completes #546, but not completely implements the `*.d.ts` files generation from the scratch._
---
**TODO**:
> feat: Add (experimental) CDS env `cds.env.typer.output_d_ts_files`
