lib/cli.js
Streamlined formatting to be more in line with `cds help`
=> Improved Formatting of `--help` Output

lib/visitor.js, test/unit/actions.test.js, test/unit/files/actions/model.cds
```cds
entity E {} actions {
action a (in: $self) {}
action b (in: many $self) {}
action c (in: $self, x: Integer) {}
}
```
result in
```ts
class E {
a: () => undefined
b: () => undefined
c: (x: number) => undefined
}
```
=> Filter out `[many] $self` Parameters From Functions

lib/visitor.js, package-lock.json, package.json, test/ast.js, test/unit/output.test.js, test/util.js
Fixes https://github.com/cap-js/cds-typer/issues/60
=> Unit Tests for Generated `index.js` Files

CHANGELOG.md, lib/csn.js
Fixes https://github.com/cap-js/cds-typer/issues/79
=> Handle compositions on inline types during draft propagation

package.json
All other cap/dev projects are fine without that → please accept this PR, unless there's a strong reason to have it
=> No prettier plugins

lib/visitor.js
=> Fallback to Definitions From Inferred Flavour in Projections

CHANGELOG.md, lib/file.js, lib/util.js, lib/visitor.js, test/ast.js, test/unit/files/scoped/model.cds, test/unit/scoped.test.js
Fixes https://github.com/cap-js/cds-typer/issues/122
=> Support Scoped Entities

CHANGELOG.md, lib/components/enum.js, lib/file.js, test/unit/enum.test.js, test/unit/files/enums/nested.cds
Fixes https://github.com/cap-js/cds-typer/issues/127
=> Export inline enums as coalesced static properties

CHANGELOG.md, lib/components/enum.js, lib/visitor.js, test/ast.js, test/unit/enum.test.js, test/unit/files/enums/actions.cds
Fixes https://github.com/cap-js/cds-typer/issues/129
=> Allow inline enums as action parameter types

CHANGELOG.md, lib/components/inline.js, lib/components/resolver.js
Fixes https://github.com/cap-js/cds-typer/issues/130
=> Print Type for Arrays of Enum Values in Action Parameter Types

CHANGELOG.md, lib/cli.js, lib/visitor.js
Addresses https://github.com/cap-js/cds-typer/issues/139
=> Change default log level to `ERROR` and make some errors more descriptive

CHANGELOG.md, lib/cli.js, lib/visitor.js
Fixes https://github.com/cap-js/cds-typer/issues/144
=> Raise error if automatically derived foreign keys are already present

lib/components/resolver.js
Fixes https://github.com/cap-js/cds-typer/issues/157
=> Remove outdated comment

lib/visitor.js, test/unit/files/type/model.cds, test/unit/type.test.js
=> Don't duplicate type aliases to enums

CHANGELOG.md, lib/components/resolver.js, lib/csn.js, lib/visitor.js, test/unit/files/projection/model.cds, test/unit/projections.test.js
Fixes https://github.com/cap-js/cds-typer/issues/167
Fixes https://github.com/cap-js/cds-typer/issues/155
Fixes https://github.com/cap-js/cds-typer/issues/81
=> Improved Projection Support

CHANGELOG.md, lib/components/resolver.js, test/unit/files/builtins/model.cds, test/unit/output.test.js
=> Map `cds.Vector` to `string`

CHANGELOG.md, lib/visitor.js, test/ast.js, test/unit/files/inheritance/elsewhere.cds, test/unit/files/inheritance/model.cds, test/unit/inheritance.test.js
=> Fix Inflection in Aspect Calls

CHANGELOG.md, lib/visitor.js
=> Only detect naming conflicts if inflections share namespace

CHANGELOG.md, lib/components/basedefs.js, lib/components/resolver.js, lib/components/typescript.js, lib/components/wrappers.js, lib/file.js, lib/visitor.js, test/ast.js, test/unit/actions.test.js, test/unit/files/actions/model.cds
=> Use Record over {}

CHANGELOG.md, lib/visitor.js, test/unit/count.test.js, test/unit/files/count/model.cds
Hi @daogrady,
here's the PR for Issue #210.
Looking forward to your feedback.
Best regards,
Jan
=> feat(visitor): Add optional $count member for plural types

CHANGELOG.md, lib/components/resolver.js, lib/visitor.js, package.json, test/tscheck.js, test/unit.jest.config.js, test/unit/files/scoped/model.cds, test/util.js
This catches problems like misspelled entities, missing imports, etc.
=> Check output transpilation of all generated types

CHANGELOG.md, lib/visitor.js, package.json, test/ast.js, test/unit/actions.test.js, test/unit/files/actions/model.cds
Fixes https://github.com/cap-js/cds-typer/issues/215
=> Handle `void` actions

.github/workflows/test.yml, package.json, test/smoke.jest.config.js, test/smoke/setup.js, test/smoke/transpilation.test.js, test/unit.jest.config.js, test/unit/inline.test.js, test/unit/typeof.test.js, test/util.js
Fixes https://github.com/cap-js/cds-typer/issues/214
=> Separate transpilation tests from structural unit tests

CHANGELOG.md, lib/visitor.js
=> Suppress error when clash is incorectly detected

CHANGELOG.md, lib/visitor.js, test/unit/aspects.test.js, test/unit/files/aspects/model.cds
Fixes https://github.com/cap-js/cds-typer/issues/270
=> Consistently name aspects in singular as well

CHANGELOG.md, lib/csn.js, lib/visitor.js, test/unit/files/views/model.cds, test/unit/views.test.js
=> Remove heritage from views and projections

CHANGELOG.md, lib/components/inline.js, lib/components/property.js, lib/components/wrappers.js, lib/file.js, lib/resolution/entity.js, lib/resolution/resolver.js, lib/typedefs.d.ts, lib/visitor.js, test/ast.js, test/unit/inline.test.js
Fixes https://github.com/cap-js/cds-typer/issues/274 (`declare`)
Fixes https://github.com/cap-js/cds-typer/issues/273 (`override`)
=> Add modifiers to properties

lib/file.js
=> Avoid newline after param doc

CHANGELOG.md, lib/visitor.js
Fixes https://github.com/cap-js/cds-typer/issues/314
=> Skip references to properties in Associations

lib/visitor.js, test/unit/actions.test.js, test/unit/events.test.js, test/unit/files/actions/model.cds, test/unit/files/events/model.cds
Fixes https://github.com/cap-js/cds-typer/issues/382 (event import error).
=> Fix event import

package.json, scripts/write-cds-typer-schema.js
@daogrady should be included before updating to 0.29.0
=> feat: update typer schema with target_module_type

CHANGELOG.md, lib/printers/javascript.js, lib/resolution/entity.js, lib/visitor.js
Fixes https://github.com/cap-js/cds-typer/issues/410
=> Generate plural types for cds aspects

CHANGELOG.md, lib/file.js
Fixes https://github.com/cap-js/cds-typer/issues/433
=> Add index.js when targeting ESM

CHANGELOG.md, lib/components/typescript.js, lib/printers/wrappers.js, test/unit/actions.test.js
Fixes https://github.com/cap-js/cds-typer/issues/445
=> Prefix builtins with globalThis.

CHANGELOG.md, lib/components/enum.js, lib/csn.js, lib/typedefs.d.ts, lib/visitor.js, test/unit/files/enums/model.cds
Fixes https://github.com/cap-js/cds-typer/issues/446
Note: do not merge before https://github.com/cap-js/cds-typer/pull/356 is sorted
=> Properly handle reference types to string fields for enums

.github/dependabot.yml, CHANGELOG.md, package.json
Also put dependabot on a grouped schedule
=> Bump peer dependency

CHANGELOG.md, lib/resolution/resolver.js, test/unit/files/localized/model.cds
=> fix: adds scope/namespace in correct order for inflected type name

CHANGELOG.md, package.json
license entry according to https://spdx.org/licenses/
=> chore: adapt license entry / rem. changelog frm. pack

CHANGELOG.md, lib/components/enum.js, lib/file.js, lib/printers/javascript.js, test/ast.js, test/unit/enum.test.js, test/unit/files/enums/nested.cds
Fixes https://github.com/cap-js/cds-typer/issues/500
=> Properly print enums in ESM style

CHANGELOG.md, lib/cli.js, package.json, test/ast.js
`cds.typer.use_entities_proxy = true` is now default behaviour.
=> Use true as default for use_entities_proxy

CHANGELOG.md, lib/compile.js
See https://github.com/cap-js/cds-typer/pull/513#issuecomment-2765460686
=> Include current version of cds-typer in model hash

CHANGELOG.md, lib/resolution/resolver.js, lib/typedefs.d.ts, lib/visitor.js, test/unit/actions.test.js, test/unit/files/actions/model.cds
Fixes https://github.com/cap-js/cds-typer/issues/516
=> Make @mandatory parameters not nullable
